In [1]:
?mod

search: mod modf mod1 module mod2pi Module modifyfield! modifyproperty! chmod



```
mod(x::Integer, r::AbstractUnitRange)
```

Find `y` in the range `r` such that $x ≡ y (mod n)$, where `n = length(r)`, i.e. `y = mod(x - first(r), n) + first(r)`.

See also [`mod1`](@ref).

# Examples

```jldoctest
julia> mod(0, Base.OneTo(3))
3

julia> mod(3, 0:2)
0
```

!!! compat "Julia 1.3"
    This method requires at least Julia 1.3.


---

```
mod(x, y)
rem(x, y, RoundDown)
```

The reduction of `x` modulo `y`, or equivalently, the remainder of `x` after floored division by `y`, i.e. `x - y*fld(x,y)` if computed without intermediate rounding.

The result will have the same sign as `y`, and magnitude less than `abs(y)` (with some exceptions, see note below).

!!! note
    When used with floating point values, the exact result may not be representable by the type, and so rounding error may occur. In particular, if the exact result is very close to `y`, then it may be rounded to `y`.


See also: [`rem`](@ref), [`div`](@ref), [`fld`](@ref), [`mod1`](@ref), [`invmod`](@ref).

```jldoctest
julia> mod(8, 3)
2

julia> mod(9, 3)
0

julia> mod(8.9, 3)
2.9000000000000004

julia> mod(eps(), 3)
2.220446049250313e-16

julia> mod(-eps(), 3)
3.0

julia> mod.(-5:5, 3)'
1×11 adjoint(::Vector{Int64}) with eltype Int64:
 1  2  0  1  2  0  1  2  0  1  2
```

---

```
rem(x::Integer, T::Type{<:Integer}) -> T
mod(x::Integer, T::Type{<:Integer}) -> T
%(x::Integer, T::Type{<:Integer}) -> T
```

Find `y::T` such that `x` ≡ `y` (mod n), where n is the number of integers representable in `T`, and `y` is an integer in `[typemin(T),typemax(T)]`. If `T` can represent any integer (e.g. `T == BigInt`), then this operation corresponds to a conversion to `T`.

# Examples

```jldoctest
julia> 129 % Int8
-127
```


In [2]:
function absoluto(x::Number)
    if x <0
        x*=-1
    end
    return x
end

function raizc(x::Number)
    a=x
    b=1.0
    while absoluto(b-a) > 0.001
        a=(a+b)/2.0
        b=x/a
    end
    return (a+b)/2
end

function seno(x::Number)
    signo=1.0
    its=14
    x0=mod(x,π)
    x0=x/2^(its)
    y=x0*x0
    if x<0 
        signo = -1.0 
    end
    if -π<x && x<=π
        for i ∈ 1:its
            y=4y*(1-y)
        end
    end
    y=signo*sqrt(y)
end

seno (generic function with 1 method)

In [33]:
using Plots

In [41]:
x=range(1,10)

1:10

In [72]:
sin(55)

-0.9997551733586199

In [71]:
seno(55)

0.00335693359375


### En python

```
import math

def seno(x):
    signo=1.0
    its=14
    x0=mod(x,π)
    x0=x/2^(its)
    y=x0*x0
    if x<0
        signo = -1.0 
    if -math.pi <x and x<=math.pi
        for i in range(its):
            y=4y*(1-y)
    return y
```

In [1]:
mutable struct Matriz3
    d0::Vector
    d1::Vector
    d2::Vector
end

function thomas(una_matriz3::Matriz3,b::Vector)
    n = length(b)
    x = zeros(n)
    d0=una_matriz3.d0
    d1=una_matriz3.d1
    d2=una_matriz3.d2
    for i = 2:n
        α = d1[i]/d0[i-1]
        d0[i] = d0[i]-α*d2[i-1]
        b[i] = b[i]-α*b[i-1]
    end
    x[n] = b[n]/d0[n]
    for i=n-1:-1:1
        x[i] = (b[i] - d2[i]*x[i+1])/d0[i]
    end
    x
end

function multMa3diagVector(matriz::Matriz3, b::Vector)
    n=length(b)
    c=zeros(n)
    tempora=0.0
    c[1] = b[1]*matriz.d0[1] +b[2]*matriz.d2[1]
    c[n] = b[n]*matriz.d0[n] +b[n-1]*matriz.d1[n-1]
    for i=2:n-1
        c[i]=b[i-1]*matriz.d1[i] + (b[i-1]*matriz.d0[i] + b[i+1]*matriz.d2[i])
    end
    return c
end

a1=[0.,3.,-4.,-2.,3.] # Inferior
a0=[2.,5.,7.,3.,-1.]
a2=[4,-2,3,1,0] #Superior
b=[6.,6.,6.,2.,2.]
eje_matriz=Matriz3(a0,a1,a2)
thomas(eje_matriz,b)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0000000000000002
 1.0000000000000002

In [3]:
eje_matriz

Matriz3([2.0, -1.0, 15.0, 3.4, -1.8823529411764706], [0.0, 3.0, -4.0, -2.0, 3.0], [4, -2, 3, 1, 0])

In [2]:
function suma(matriz1::Matriz3, matriz2::Matriz3)
    n=length(matriz1.d0)
    a=zeros(n)
    b=zeros(n)
    c=zeros(n)
    resultado=Matriz3(a,b,c)
    for i ∈ 1:n
        resultado.d0[i]=matriz1.d0[i]+matriz2.d0[i]
        resultado.d1[i]=matriz1.d1[i]+matriz2.d1[i]
        resultado.d2[i]=matriz1.d2[i]+matriz2.d2[i]
    end
    return resultado
end

suma (generic function with 1 method)

In [3]:
function suma2(matriz1::Matriz3,matriz2::Matriz3)
    n = length(matriz1.d0)
    resultado = Matriz3(zeros(n),zeros(n),zeros(n))
    for i in 1:n
        resultado.d0[i] += matriz2.d0[i]
        resultado.d1[i] += matriz2.d1[i]
        resultado.d2[i] += matriz2.d2[i]
    end
    resultado
end

suma2 (generic function with 1 method)

In [3]:
eje_matriz

Matriz3([2.0, -1.0, 15.0, 3.4, -1.8823529411764706], [0.0, 3.0, -4.0, -2.0, 3.0], [4, -2, 3, 1, 0])

In [4]:
function test(a::Vector)
    println(a)
end

test (generic function with 1 method)

In [4]:
a1=[0.,3.,-4.,-2.,3.]
a0=[2.,5.,7.,3.,-1.]
a2=[4,-2,3,1,0]
b=[6.,6.,6.,2.,2.]
eje_matriz=Matriz3(a0,a1,a2)

eje_2=Matriz3(a0,a1,a2)

Matriz3([2.0, 5.0, 7.0, 3.0, -1.0], [0.0, 3.0, -4.0, -2.0, 3.0], [4, -2, 3, 1, 0])

In [5]:
eje_matriz

Matriz3([2.0, 5.0, 7.0, 3.0, -1.0], [0.0, 3.0, -4.0, -2.0, 3.0], [4, -2, 3, 1, 0])

In [22]:
@time suma(eje_matriz,eje_2)

  0.000016 seconds (34 allocations: 800 bytes)


Matriz3([4.0, 10.0, 14.0, 6.0, -2.0], [0.0, 6.0, -8.0, -4.0, 6.0], [8.0, -4.0, 6.0, 2.0, 0.0])

In [23]:
@time suma2(eje_matriz,eje_2)

  0.000028 seconds (44 allocations: 960 bytes)


Matriz3([2.0, 5.0, 7.0, 3.0, -1.0], [0.0, 3.0, -4.0, -2.0, 3.0], [4.0, -2.0, 3.0, 1.0, 0.0])

In [7]:
eje_matriz

Matriz3([2.0, 5.0, 7.0, 3.0, -1.0], [0.0, 3.0, -4.0, -2.0, 3.0], [4, -2, 3, 1, 0])

In [8]:
eje_2

Matriz3([2.0, 5.0, 7.0, 3.0, -1.0], [0.0, 3.0, -4.0, -2.0, 3.0], [4, -2, 3, 1, 0])

In [10]:
a1

5-element Vector{Float64}:
  0.0
  6.0
 -8.0
 -4.0
  6.0

In [11]:
a2

5-element Vector{Int64}:
  8
 -4
  6
  2
  0

In [12]:
a0

5-element Vector{Float64}:
  4.0
 10.0
 14.0
  6.0
 -2.0

In [24]:
a=[2,3,4]
b=a
b[2]=4

4

In [25]:
a

3-element Vector{Int64}:
 2
 4
 4

In [26]:
?copy

search: copy copy! copyto! copysign deepcopy unsafe_copyto! circcopy!



```
copy(x)
```

Create a shallow copy of `x`: the outer structure is copied, but not all internal values. For example, copying an array produces a new array with identically-same elements as the original.

See also [`copy!`](@ref Base.copy!), [`copyto!`](@ref).

---

```
copy(A::Transpose)
copy(A::Adjoint)
```

Eagerly evaluate the lazy matrix transpose/adjoint. Note that the transposition is applied recursively to elements.

This operation is intended for linear algebra usage - for general data manipulation see [`permutedims`](@ref Base.permutedims), which is non-recursive.

# Examples

```jldoctest
julia> A = [1 2im; -3im 4]
2×2 Matrix{Complex{Int64}}:
 1+0im  0+2im
 0-3im  4+0im

julia> T = transpose(A)
2×2 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1+0im  0-3im
 0+2im  4+0im

julia> copy(T)
2×2 Matrix{Complex{Int64}}:
 1+0im  0-3im
 0+2im  4+0im
```


In [27]:
matriz_copia=copy(eje_matriz)

LoadError: MethodError: no method matching copy(::Matriz3)
Closest candidates are:
  copy(::SuiteSparse.CHOLMOD.Dense{Tv}) where Tv<:Union{Float64, ComplexF64} at C:\ProgramData\Julia-1.7.2\share\julia\stdlib\v1.7\SuiteSparse\src\cholmod.jl:416
  copy(::LinearAlgebra.UpperTriangular) at C:\ProgramData\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\triangular.jl:46
  copy(::Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}}) at C:\ProgramData\Julia-1.7.2\share\julia\base\broadcast.jl:1071
  ...

In [28]:
using Pkg
Pkg.add("PyCall")

    Updating registry at `C:\Users\Pedro Elias\.julia\registries\General.toml`
   Resolving package versions...
  No Changes to `C:\Users\Pedro Elias\.julia\environments\v1.7\Project.toml`
  No Changes to `C:\Users\Pedro Elias\.julia\environments\v1.7\Manifest.toml`


In [3]:
using Pkg

In [1]:
using PyCall

In [4]:
Pkg.status()

      Status `C:\Users\Pedro Elias\.julia\environments\v1.7\Project.toml`
  [a2cac450] ColorBrewer v0.4.0
  [35d6a980] ColorSchemes v3.17.1
  [3da002f7] ColorTypes v0.11.0
  [5ae59095] Colors v0.12.8
  [8f4d0f93] Conda v1.7.0
  [a93c6f00] DataFrames v1.3.5
  [0c46a032] DifferentialEquations v7.1.0
  [7073ff75] IJulia v1.23.2
  [033835bb] JLD2 v0.4.22
  [b964fa9f] LaTeXStrings v1.3.0
  [442fdcdd] Measures v0.3.1
  [91a5bcdd] Plots v1.27.4
  [438e738f] PyCall v1.93.1
  [d330b81b] PyPlot v2.10.0
  [276daf66] SpecialFunctions v2.1.4
  [c3572dad] Sundials v4.9.3
  [8bb1440f] DelimitedFiles
  [8ba89e20] Distributed
  [37e2e46d] LinearAlgebra


In [6]:
mate=pyimport("math")
mate.sin(mate.pi/4)

0.7071067811865476

In [8]:
numpy = pyimport("numpy")

LoadError: PyError (PyImport_ImportModule

The Python package numpy could not be imported by pyimport. Usually this means
that you did not install numpy in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the numpy module, you can
use `pyimport_conda("numpy", PKG)`, where PKG is the Anaconda
package that contains the module numpy, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'numpy'")


In [9]:
Conda.add(numpy)

LoadError: UndefVarError: Conda not defined

In [10]:
pyimport_conda("numpy", PKG)

LoadError: UndefVarError: PKG not defined

In [11]:
using Conda

In [12]:
Conda.add("numpy")

┌ Info: Running `conda install -y numpy` in root environment
└ @ Conda C:\Users\Pedro Elias\.julia\packages\Conda\x2UxR\src\Conda.jl:127
failed to create process.


In [13]:
numpy=pyimport("numpy")

LoadError: PyError (PyImport_ImportModule

The Python package numpy could not be imported by pyimport. Usually this means
that you did not install numpy in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the numpy module, you can
use `pyimport_conda("numpy", PKG)`, where PKG is the Anaconda
package that contains the module numpy, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'numpy'")


In [ ]:
a=numpy1.zeros(10) #np.zeros
typeof(a) # Sera un vector

## En 

B=numpy.zeros([3,3])

In [16]:

plt = pyimport("matplotlib.pyplot")
x = range(0; stop=2*pi, length=1000; y=sin.(3*x+4*cos.(2*x)));
plt.plot(x,y,color="red", linewidth=2.0, linestyle="--")
plt.savefig("test.png");

LoadError: PyError (PyImport_ImportModule

The Python package matplotlib.pyplot could not be imported by pyimport. Usually this means
that you did not install matplotlib.pyplot in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the matplotlib.pyplot module, you can
use `pyimport_conda("matplotlib.pyplot", PKG)`, where PKG is the Anaconda
package that contains the module matplotlib.pyplot, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'matplotlib'")


In [17]:
?@pyinclude

```
@pyinclude(filename)
```

Execute the Python script in the file `filename` as if it were in a `py""" ... """` block, e.g. so that any globals defined in `filename` are available to subsequent `py"..."` evaluations.

(Unlike `py"..."`, however, `@pyinclude` does not interpolate Julia variables into `$var` expressions — the `filename` script must be pure Python.)


In [19]:
?"""

search: """



```
"""
```

`"""` is used to delimit string literals. Strings created by triple quotation marks can contain `"` characters without escaping and are dedented to the level of the least-indented line. This is useful for defining strings within code that is indented.

# Examples

```jldoctest
julia> """Hello World!"""
"Hello World!"

julia> """Contains "quote" characters"""
"Contains \"quote\" characters"

julia> """
         Hello,
         world."""
"Hello,\nworld."
```

See also [`"`](@ref ")


In [20]:
?@

search: @ @doc @cmd @warn @view @time @task @sync @simd @show @lock @info @goto



```
@
```

The at sign followed by a macro name marks a macro call. Macros provide the ability to include generated code in the final body of a program. A macro maps a tuple of arguments, expressed as space-separated expressions or a function-call-like argument list, to a returned *expression*. The resulting expression is compiled directly into the surrounding code. See [Metaprogramming](@ref man-macros) for more details and examples.


## invocando código C desde Julia

In [ ]:
#=
@ccall biblioteca.nom_funcion(arg1::tipoarg, arg2::tipoarg, ...)::tiporegresado
@ccall nombre_fun(arg1::tipoarg, arg2::tipoarg, ...)::tiporegresado
@ccall $apuntador_funcion(arg1::tipoarg, arg2::tipoarg, ...)::tiporegresado
=#

In [22]:
?@ccall

```
@ccall library.function_name(argvalue1::argtype1, ...)::returntype
@ccall function_name(argvalue1::argtype1, ...)::returntype
@ccall $function_pointer(argvalue1::argtype1, ...)::returntype
```

Call a function in a C-exported shared library, specified by `library.function_name`, where `library` is a string constant or literal. The library may be omitted, in which case the `function_name` is resolved in the current process. Alternatively, `@ccall` may also be used to call a function pointer `$function_pointer`, such as one returned by `dlsym`.

Each `argvalue` to `@ccall` is converted to the corresponding `argtype`, by automatic insertion of calls to `unsafe_convert(argtype, cconvert(argtype, argvalue))`. (See also the documentation for [`unsafe_convert`](@ref Base.unsafe_convert) and [`cconvert`](@ref Base.cconvert) for further details.) In most cases, this simply results in a call to `convert(argtype, argvalue)`.

# Examples

```
@ccall strlen(s::Cstring)::Csize_t
```

This calls the C standard library function:

```
size_t strlen(char *)
```

with a Julia variable named `s`. See also `ccall`.

Varargs are supported with the following convention:

```
@ccall printf("%s = %d"::Cstring ; "foo"::Cstring, foo::Cint)::Cint
```

The semicolon is used to separate required arguments (of which there must be at least one) from variadic arguments.

Example using an external library:

```
# C signature of g_uri_escape_string:
# char *g_uri_escape_string(const char *unescaped, const char *reserved_chars_allowed, gboolean allow_utf8);

const glib = "libglib-2.0"
@ccall glib.g_uri_escape_string(my_uri::Cstring, ":/"::Cstring, true::Cint)::Cstring
```

The string literal could also be used directly before the function name, if desired `"libglib-2.0".g_uri_escape_string(...`


In [83]:
t=@ccall clock()::Float32

7.337492f23

In [81]:
?@ccall clock()

```
@ccall library.function_name(argvalue1::argtype1, ...)::returntype
@ccall function_name(argvalue1::argtype1, ...)::returntype
@ccall $function_pointer(argvalue1::argtype1, ...)::returntype
```

Call a function in a C-exported shared library, specified by `library.function_name`, where `library` is a string constant or literal. The library may be omitted, in which case the `function_name` is resolved in the current process. Alternatively, `@ccall` may also be used to call a function pointer `$function_pointer`, such as one returned by `dlsym`.

Each `argvalue` to `@ccall` is converted to the corresponding `argtype`, by automatic insertion of calls to `unsafe_convert(argtype, cconvert(argtype, argvalue))`. (See also the documentation for [`unsafe_convert`](@ref Base.unsafe_convert) and [`cconvert`](@ref Base.cconvert) for further details.) In most cases, this simply results in a call to `convert(argtype, argvalue)`.

# Examples

```
@ccall strlen(s::Cstring)::Csize_t
```

This calls the C standard library function:

```
size_t strlen(char *)
```

with a Julia variable named `s`. See also `ccall`.

Varargs are supported with the following convention:

```
@ccall printf("%s = %d"::Cstring ; "foo"::Cstring, foo::Cint)::Cint
```

The semicolon is used to separate required arguments (of which there must be at least one) from variadic arguments.

Example using an external library:

```
# C signature of g_uri_escape_string:
# char *g_uri_escape_string(const char *unescaped, const char *reserved_chars_allowed, gboolean allow_utf8);

const glib = "libglib-2.0"
@ccall glib.g_uri_escape_string(my_uri::Cstring, ":/"::Cstring, true::Cint)::Cstring
```

The string literal could also be used directly before the function name, if desired `"libglib-2.0".g_uri_escape_string(...`


In [68]:
t2=@ccall clock()::Int32

4744473

In [43]:
mi_shell=@ccall getenv("SHELL"::Cstring)::Cstring

Cstring(0x0000000000000000)

In [38]:
unsafe_string(mi_shell)

LoadError: ArgumentError: cannot convert NULL to string

In [40]:
function valorVariable(var::AbstractString)
    valor = @ccall getenv(var::Cstring)::Cstring
    if valor == C_NULL
        error("getenv: Variable de ambiente no encontrada: ", var)
    end
    return unsage_string(valor)
end

valorVariable("mi_shell")
    

LoadError: getenv: Variable de ambiente no encontrada: mi_shell

ldd #en C o en un .out nos dice que librerias fueron usadas para su compilación